name: Process Tokens
on:
  push:
    branches: [ tokens ]

jobs:
  process-tokens:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      - name: Transform Tokens and Generate Variables
      - run: npm run transform-tokens

      - name: Commit and push changes
        run: |
          git config --global user.name "cagespence"
          git config --global user.email "cagespence@gmail.com"

          git add -A
          git commit -m "automated: processed tokens"
          git push
